CREATE TABLE T_FIRR_LICENCAS (
                                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                                NOME VARCHAR2(255),
                                ORGAO_EMISSOR VARCHAR2(255),
                                DATA_VALIDADE DATE,
                                STATUS VARCHAR2(255),
                                PRIMARY KEY (ID)
);